### ISSUE TITLE
MVC architecture

### ISSUE THREAD

**Issue by ioanniskousis** [PhillipUg/library#2]
- create a module holding the total library database and manages addition, updates and deletions
- create a class for Book holding info of each book
- the library should know about books but a book should not know about the library
- the rendering environment should setup events calling the controller (app.js).. then the controller should manage the database (the library)
- inside the library module use localStorage to save and retrieve the library data having methods like load() and save() to call from the controller

**Comment by PhillipUg** [comment]
Thanks for your time and advice. I will make sure to implement your suggestions.
