### ISSUE TITLE
MVC principles

### ISSUE THREAD

**Issue by ioanniskousis** [PhillipUg/library#4]
Use a controller entity (class || module || function) which will do (you have app.js): 
- read whatever is mandatory to know before paint the screen, this means "Read The Database"
  - so define a variable pointing to that data (inside app.js)
- filter this data depending on the program state
- and send this data to the interface module to create the users screen
- building the users screen must prepare events that run a callBack function held in the controller 
- so you have to add a pointer to that callBack function.
- so change command render(books) - > render(books, eventsListener) .. where eventsListener is a function inside the app.js (the controller)

**Comment by PhillipUg** [comment]
noted with thanks. will try to use this pattern for this and other projects.
